apiVersion: v1
kind: Service
metadata:
  name: reverent-meera-c43d0e7f97-srv
spec:
  selector:
    app: reverent-meera-c43d0e7f97
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP